[workspace]
channels = ["conda-forge"]
name = "cv_exercises"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.5,<3"
opencv = ">=4.11.0,<5"
matplotlib = ">=3.10.1,<4"
scipy = ">=1.15.2,<2"
imageio = ">=2.37.0,<3"
networkx = ">=3.4.2,<4"
scikit-learn = ">=1.6.1,<2"
scikit-image = ">=0.25.2,<0.26"
pytorch = ">=2.6.0,<3"
torchvision = ">=0.21.0,<0.22"
tensorboard = ">=2.19.0,<3"
jupyterlab = ">=4.4.1,<5"
python = ">=3.12.10,<3.13"
